### ISSUE TITLE
Please update public docker image

### ISSUE THREAD

**Issue by xeroc** [LOQ9/drone-nomad#12]
The image to this project on https://hub.docker.com/r/drone/drone-runner-nomad/tags
is 3 years old. Would you mind updating the image? Thank you!

**Comment by marcotuna** [comment]
Hi @xeroc, the docker image you are referring to does not correspond to this project. The corresponding Git repository seems to be available in the following Git repository (seems to be archived): https://github.com/drone-runners/drone-runner-nomad

For this project the docker image is available here: https://hub.docker.com/r/loq9/drone-nomad.

**Comment by xeroc** [comment]
Ah, great. Thanks
